# Enforce canonical domain (www)
[[redirects]]
  from = "https://paultakisaki.com/*"
  to = "https://www.paultakisaki.com/:splat"
  status = 301
  force = true

# Enforce HTTPS
[[redirects]]
  from = "http://www.paultakisaki.com/*"
  to = "https://www.paultakisaki.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://paultakisaki.com/*"
  to = "https://www.paultakisaki.com/:splat"
  status = 301
  force = true

# Remove index.html from URLs
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "/*/index.html"
  to = "/:splat/"
  status = 301
  force = true

# Existing redirects
[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 301
  force = true

[[redirects]]
  from = "/articles/strategic-failure.html"
  to = "/insights/strategy.html"
  status = 301
  force = true

[[redirects]]
  from = "/insights/wrong-plane-right-destination"
  to = "/insights/wrong-plane.html"
  status = 301
  force = true

[[redirects]]
  from = "/leadership-accelerator"
  to = "/leadership-accelerator.html"
  status = 301
  force = true

# Redirect old blog paths that might be indexed
[[redirects]]
  from = "/blogs/index.html"
  to = "/insights/Insights.html"
  status = 301
  force = true

[[redirects]]
  from = "/blogs/*"
  to = "/insights/:splat"
  status = 301
  force = true

# Cache headers for static assets
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=604800, must-revalidate"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# >> CONFIRMED <<